### ISSUE TITLE
USER STORY: Create Posts

### ISSUE THREAD

**Issue by sejungkwak** [sejungkwak/krie#9]
As a **registered user**, I want to **create a post to ask about others' recent experiences with the immigration office** so that I can **prepare for my upcoming appointment**.

**Comment by sejungkwak** [comment]
## Tasks

- [x] Displaying the form
- [x] Saving the data
- [x] Rendering different pages for the post and cancel buttons
- [x] Styling
